# swagger.yml

openapi: 3.0.0

info:
  title: "Groceries Flask REST API"
  description: "An API about products in a supermarket"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Product:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        category:
          type: "string"
        quantity:
          type: "integer"
        price:
          type: "number"
  parameters:
    name:
      name: "name"
      description: "Name of the product to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /products:
    get:
      operationId: "products.read_all"
      tags:
        - "Products"
      summary: "Read the list of products"
      responses:
        "200":
          description: "Successfully read products list"
    post:
      operationId: "products.create"
      tags:
        - "Products"
      summary: "Create a product"
      requestBody:
        x-body-name: "product"
        description: "Product to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: "Successfully created person"
  /products/{name}:
    get:
      operationId: "products.read_one"
      tags:
        - Products
      summary: "Read one product"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read product"
    put:
      tags:
        - Products
      operationId: "products.update"
      summary: "Update a product"
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        x-body-name: "product"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: "Successfully updated person"
    delete:
      tags:
        - Products
      operationId: "products.delete"
      summary: "Delete a product"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted person"